import tensorflow  as tf
initializer = tf.keras.initializers.RandomNormal(mean=0., stddev=1.)
values = initializer(shape=(2, 2))
print("*"*100)
print("*"*10)
print("RandomNormal")
print(values)
print("*"*10)

initializer = tf.keras.initializers.RandomUniform(minval=0., maxval=1.)
values = initializer(shape=(2, 2))
print("*"*10)
print("RandomUniform")
print(values)
print("*"*10)

initializer = tf.keras.initializers.TruncatedNormal(mean=0., stddev=1.)
values = initializer(shape=(2, 2))
print("*"*10)
print("TruncatedNormal")
print(values)
print("*"*10)

initializer = tf.keras.initializers.Zeros()
values = initializer(shape=(2, 2))
print("*"*10)
print("Zeros")
print(values)
print("*"*10)

initializer = tf.keras.initializers.Ones()
values = initializer(shape=(2, 2))
print("*"*10)
print("Ones")
print(values)
print("*"*10)
initializer = tf.keras.initializers.GlorotNormal()
values = initializer(shape=(2, 2))
print("*"*10)
print("GlorotNormal")
print(values)
print("*"*10)
initializer = tf.keras.initializers.GlorotUniform()
values = initializer(shape=(2, 2))
print("*"*10)
print("GlorotUniform")
print(values)
print("*"*10)
initializer = tf.keras.initializers.HeNormal()
values = initializer(shape=(2, 2))
print("*"*10)
print("HeNormal")
print(values)
print("*"*10)
initializer = tf.keras.initializers.HeUniform()
values = initializer(shape=(2, 2))
print("*"*10)
print("HeUniform")
print(values)
print("*"*10)
initializer = tf.keras.initializers.Identity()
values = initializer(shape=(2, 2))
print("*"*10)
print("Identity")
print(values)
print("*"*10)
initializer = tf.keras.initializers.Orthogonal()
values = initializer(shape=(2, 2))
print("*"*10)
print("Orthogonal")
print(values)
print("*"*10)
initializer = tf.keras.initializers.Constant(3.)
values = initializer(shape=(2, 2))
print("*"*10)
print("Constant")
print(values)
print("*"*10)